---
kind: pipeline
type: docker
name: default

clone:
  depth: 10

steps:

- name: configure
  image: scemama666/qp2_env
  commands:
  - ./configure -i all -c ./config/gfortran_debug.cfg
  - bash -c "source quantum_package.rc ; qp plugins download https://gitlab.com/scemama/qp_plugins_scemama"
  - bash -c "source quantum_package.rc ; qp plugins install champ"

- name: compile
  image: scemama666/qp2_env
  commands:
  - bash -c "source quantum_package.rc ; exec ninja"

- name: testing
  image: scemama666/qp2_env
  commands:
  - bash -c "source quantum_package.rc ; TRAVIS=1 qp_test -a"


- name: re-configure
  image: ubuntu
  commands:
  - ./configure -i all -c ./config/gfortran_avx.cfg

- name: compile
  image: ubuntu
  commands:
  - bash -c "source quantum_package.rc ; ninja"

- name: testing
  image: ubuntu
  commands:
  - bash -c "source quantum_package.rc ; qp_test -a"

