---
kind: pipeline
type: docker
name: default

clone:
  depth: 10

steps:
- name: setup
  image: ubuntu
  commands:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    curl \
    wget \
    python3 \
    gfortran \
    gcc \
    g++ \
    make \
    build-essential \
    rsync \
    unzip \
    libopenblas-dev \
    pkg-config \
    m4 \
    python3
  - ln -s /usr/bin/python3 /usr/bin/python


- name: configure
  image: ubuntu
  commands:
  - ./configure -i all -c ./config/gfortran_debug.cfg
  - source quantum_package.rc ; qp plugins download https://gitlab.com/scemama/qp_plugins_scemama
  - source quantum_package.rc ; qp plugins install champ

- name: compile
  image: ubuntu
  commands:
  - source quantum_package.rc ; ninja

- name: testing
  image: ubuntu
  commands:
  - source quantum_package.rc ; TRAVIS=1 qp_test -a


- name: re-configure
  image: ubuntu
  commands:
  - ./configure -i all -c ./config/gfortran_avx.cfg

- name: compile
  image: ubuntu
  commands:
  - source quantum_package.rc ; ninja

- name: testing
  image: ubuntu
  commands:
  - source quantum_package.rc ; qp_test -a

