---
kind: pipeline
type: docker
name: gfortran-debug

clone:
  depth: 10

steps:

- name: configure
  image: scemama666/qp2_env
  commands:
  - ./configure -i all -c ./config/gfortran_debug.cfg
  - bash -c "source quantum_package.rc ; exec qp_plugins download https://gitlab.com/scemama/qp_plugins_scemama"
  - bash -c "source quantum_package.rc ; exec qp_plugins install champ"

- name: compile
  image: scemama666/qp2_env
  commands:
  - bash -c "source quantum_package.rc ; exec ninja"

- name: testing
  image: scemama666/qp2_env
  commands:
  - bash -c "source quantum_package.rc ; TRAVIS=1 exec qp_test -a"

---
kind: pipeline
type: docker
name: gfortran-avx

clone:
  depth: 10

steps:

- name: configure
  image: scemama666/qp2_env
  commands:
  - ./configure -i all -c ./config/gfortran_avx.cfg

- name: compile
  image: scemama666/qp2_env
  commands:
  - bash -c "source quantum_package.rc ; exec ninja"

- name: testing
  image: scemama666/qp2_env
  commands:
  - bash -c "source quantum_package.rc ; exec qp_test -a"

