#sudo: true
#before_script:
#  - sudo apt-get update -q
#  - sudo apt-get remove curl
#  - sudo apt-get remove zlib1g-dev
#  - sudo apt-get install autoconf
#  - sudo rm /usr/local/bin/bats

os: linux

dist: bionic

sudo: false

compiler: gfortran

addons:
  apt:
    packages:
    - gfortran
    - gcc
    - libatlas-base-dev
    - liblapack-dev
    - libblas-dev
    - wget
    - eatmydata

env:
  - OPAMROOT=$HOME/.opam

cache:
  directories:
  - $HOME/.opam/
  - $HOME/cache

language: python
python:
    - "3.7"

stages:
  - configuration
  - compilation
  - testing

jobs:
  include:
    - stage: configuration
      script: eatmydata travis/configuration.sh
    - stage: compilation
      script: eatmydata travis/compilation.sh
    - stage: testing
      script: eatmydata travis/testing.sh

